# Clone the wabue members area

- name: "Create temporary path"
  hosts: ansible_master
  tags:
    - "always"
  tasks:
    - name: "Create temporary path"
      tempfile:
        state: "directory"
      register: "local_tempdir"

- name: "Dump database"
  tags:
    - "database"
  hosts: database_source
  tasks:
    - name: "Create temporary file"
      tempfile:
      register: "tempfile"
    - name: "Dump database"
      mysql_db:
        name: "{{ database_source_name }}"
        login_user: "{{ database_source_username }}"
        login_password: "{{ database_source_password }}"
        state: "dump"
        target: "{{ tempfile.path }}.sql"
    - name: "Download dump"
      fetch:
        src: "{{ tempfile.path }}.sql"
        dest: "{{ hostvars['ansible_master']['local_tempdir'].path }}/database.sql"
        flat: "yes"
    - name: "Cleanup"
      file:
        path: "{{ tempfile }}"
        state: "absent"

- name: "Fix database dump"
  tags:
    - "database"
    - "uncheckable"
  hosts: ansible_master
  tasks:
    # Uses sed command instead of replace because auf https://github.com/ansible/ansible/issues/64353
    - name: "Fix URL"
      command: "sed -i -re 's#{{ url_source }}#{{ url_destination }}#gi' {{ local_tempdir.path }}/database.sql warn=no"
    - name: "Fix data path"
      command: "sed -i -re 's#{{ data_folder_source }}#{{ data_folder_destination }}#gi' {{ local_tempdir.path }}/database.sql warn=no"
    - name: "Fix application path"
      command: "sed -i -re 's#{{ application_folder_source }}#{{ application_folder_destination }}#gi' {{ local_tempdir.path }}/database.sql warn=no"
    - name: "Remove create db line"
      command: "sed -i -re '/CREATE DATABASE.*/d' {{ local_tempdir.path }}/database.sql warn=no"
    - name: "Remove use db line"
      command: "sed -i -re '/USE `.*/d' {{ local_tempdir.path }}/database.sql warn=no"

- name: "Restore dump"
  tags:
    - "database"
  hosts: database_destination
  tasks:
    - name: "Create temporary directory"
      tempfile:
        state: "directory"
      register: "remote_tempdir"
    - name: "Upload clean script"
      template:
        dest: "{{ remote_tempdir.path }}/dropAllTables.sql"
        src: "templates/dropAllTables.sql.jinja"
    - name: "Upload dump"
      tags:
        - "uncheckable"
      copy:
        src: "{{ hostvars['ansible_master']['local_tempdir'].path }}/database.sql"
        dest: "{{ remote_tempdir.path }}"
    - name: "Clean database"
      mysql_db:
        name: "{{ database_destination_name }}"
        login_user: "{{ database_destination_username }}"
        login_password: "{{ database_destination_password }}"
        state: "import"
        target: "{{ remote_tempdir.path }}/dropAllTables.sql"
    - name: "Import dump"
      mysql_db:
        name: "{{ database_destination_name }}"
        login_user: "{{ database_destination_username }}"
        login_password: "{{ database_destination_password }}"
        state: "import"
        target: "{{ remote_tempdir.path }}/database.sql"
    - name: "Cleanup"
      file:
        path: "{{ remote_tempdir.path }}"
        state: "absent"

- name: "Clean up locally"
  tags:
    - "database"
    - "uncheckable"
  hosts: ansible_master
  tasks:
    - name: "Remove database dump"
      file:
        path: "{{ local_tempdir.path }}/database.sql"
        state: "absent"

- name: "Transfer application from source"
  tags:
    - "application"
  hosts: application_source
  tasks:
    - name: "Create temporary file"
      tempfile:
      register: "application_archive"
    - name: "Archive application folder"
      archive:
        path: 
          - "{{ application_folder_source }}/*"
          - "{{ application_folder_source }}/.htaccess"
        dest: "{{ application_archive.path }}.tar.bz2"
        format: "bz2"
    - name: "Download application folder"
      fetch:
        src: "{{ application_archive.path }}.tar.bz2"
        dest: "{{ hostvars['ansible_master']['local_tempdir'].path }}/application.tar.bz2"
        flat: "yes"
    - name: "Cleanup"
      file:
        path: "{{ application_archive.path }}.tar.bz2"
        state: "absent"

- name: "Transfer application to destination"
  tags:
    - "application"
  hosts: application_destination
  tasks:
    - name: "Create temporary path"
      tempfile:
        state: "directory"
      register: "remote_tempdir"
    - name: "Copy application archive"
      tags:
        - "uncheckable"
      copy:
        src: "{{ hostvars['ansible_master']['local_tempdir'].path }}/application.tar.bz2"
        dest: "{{ remote_tempdir.path }}"
    - name: "Remove old application folder"
      file:
        path: "{{ application_folder_destination }}"
        state: "absent"
    - name: "Recreate old application folder"
      file:
        path: "{{ application_folder_destination }}"
        state: "directory"
        recurse: "yes"
    - name: "Unarchive application archive"
      tags:
        - "uncheckable"
      unarchive:
        src: "{{ remote_tempdir.path }}/application.tar.bz2"
        dest: "{{ application_folder_destination }}"
    - name: "Cleanup"
      tags:
        - "uncheckable"
      file:
        path: "{{ remote_tempdir.path }}"
        state: "absent"

- name: "Clean up locally"
  tags:
    - "application"
    - "uncheckable"
  hosts: ansible_master
  tasks:
    - name: "Remove application archive"
      file:
        path: "{{ local_tempdir.path }}/application.tar.bz2"
        state: "absent"

- name: "Fix application settings"
  tags:
    - "application"
    - "application_settings"
  hosts: application_destination
  tasks:
    - name: "Add dbhost"
      lineinfile:
        path: "{{ application_folder_destination }}/elgg-config/settings.php"
        line: "$CONFIG->dbhost = '{{ database_destination_host }}';"
    - name: "Add dbname"
      lineinfile:
        path: "{{ application_folder_destination }}/elgg-config/settings.php"
        line: "$CONFIG->dbname = '{{ database_destination_name }}';"
    - name: "Add dbuser"
      lineinfile:
        path: "{{ application_folder_destination }}/elgg-config/settings.php"
        line: "$CONFIG->dbuser = '{{ database_destination_username }}';"
    - name: "Add dbpass"
      lineinfile:
        path: "{{ application_folder_destination }}/elgg-config/settings.php"
        line: "$CONFIG->dbpass = '{{ database_destination_password }}';"
    - name: "Add dataroot"
      lineinfile:
        path: "{{ application_folder_destination }}/elgg-config/settings.php"
        line: "$CONFIG->dataroot = '{{ data_folder_destination }}';"

- name: "Transfer data folder from source"
  tags:
    - "data"
  hosts: application_source
  tasks:
    - name: "Create temporary file"
      tempfile:
      register: "data_archive"
    - name: "Archive data folder"
      archive:
        path: "{{ data_folder_source }}/*"
        dest: "{{ data_archive.path }}.tar.bz2"
        format: "bz2"
        exclude_path:
          - "system_cache"
          - "views_simplecache"
    - name: "Download data archive"
      tags:
        - "uncheckable"
      fetch:
        src: "{{ data_archive.path }}.tar.bz2"
        dest: "{{ hostvars['ansible_master']['local_tempdir'].path }}/data.tar.bz2"
        flat: "yes"
    - name: "Cleanup"
      tags:
        - "uncheckable"
      file:
        path: "{{ data_archive.path }}.tar.bz2"
        state: "absent"

- name: "Transfer data folder to destination"
  tags:
    - "data"
  hosts: application_destination
  tasks:
    - name: "Create temporary path"
      tempfile:
        state: "directory"
      register: "remote_tempdir"
    - name: "Upload data archive"
      tags: 
        - "uncheckable"
      copy:
        src: "{{ hostvars['ansible_master']['local_tempdir'].path }}/data.tar.bz2"
        dest: "{{ remote_tempdir.path }}"
    - name: "Remove old data folder"
      file:
        path: "{{ data_folder_destination }}"
        state: "absent"
    - name: "Create data folder"
      file:
        path: "{{ data_folder_destination }}"
        state: "directory"
        recurse: "yes"
    - name: "Unarchive data archive"
      tags:
        - "uncheckable"
      unarchive:
        src: "{{ remote_tempdir.path }}/data.tar.bz2"
        dest: "{{ data_folder_destination }}"
    - name: "Set owner of event_calendar fork"
      file:
        path: "{{ data_folder_destination }}"
        owner: "{{ owner_destination }}"
        group: "{{ group_destination }}"
        state: "directory"
        recurse: "yes"
    - name: "Clean up"
      tags:
        - "uncheckable"
      file:
        path: "{{ remote_tempdir.path }}"
        state: "absent"

- name: "Clean up locally"
  tags:
    - "data"
    - "uncheckable"
  hosts: ansible_master
  tasks:
    - name: "Remove data archive"
      file:
        path: "{{ local_tempdir.path }}/data.tar.bz2"
        state: "absent"

- name: "Add file transport module"
  tags:
    - "integration"
    - "uncheckable"
  hosts: application_destination
  tasks:
    - name: "Create temporary folder"
      tempfile:
        state: "directory"
      register: "remote_tempdir"
    - name: "Download file transport module"
      get_url:
        url: "https://github.com/wabuehamm/elgg-plugin-filetransport/archive/master.zip"
        dest: "{{ remote_tempdir.path }}/master.zip"
    - name: "Unzip file transport module"
      unarchive:
        src: "{{ remote_tempdir.path }}/master.zip"
        dest: "{{ remote_tempdir.path }}"
        owner: "{{ owner_destination }}"
        group: "{{ group_destination }}"
    - name: "Move file transport module to module directory"
      synchronize:
        src: "{{ remote_tempdir.path }}/elgg-plugin-filetransport-master/"
        dest: "{{ application_folder_destination }}/mod/filetransport"
        recursive: "yes"
        delete: "yes"
        owner: "yes"
        group: "yes"
    - name: "Clean up"
      file:
        path: "{{ remote_tempdir.path }}"
        state: "absent"

- name: "Run updates"
  tags:
    - "updates"
    - "updates_tasks"
  hosts: application_destination
  tasks:
    - name: "Include update tasks"
      include_tasks:
        file: "updates/{{ item }}.yaml"
      loop: "{{ update_tasks }}"

- name: "Run database updates"
  tags:
    - "updates"
    - "updates_sql"
    - "uncheckable"
  hosts: database_destination
  tasks:
    - include_tasks:
        file: "tasks/update_tasks_sql.yaml"
      loop: "{{ update_tasks_sql }}"

- name: "Activate filetransport plugin"
  hosts: application_destination
  tags:
    - "uncheckable"
    - "integration"
  tasks:
    - name: "Activate filetransport plugin"
      command: "php vendor/bin/elgg-cli plugins:activate -- filetransport chdir={{ application_folder_destination }}"

- name: "Fix ownership"
  hosts: application_destination
  tasks:
    - name: "Set owner of application folder"
      file:
        path: "{{ application_folder_destination }}"
        owner: "{{ owner_destination }}"
        group: "{{ group_destination }}"
        state: "directory"
        recurse: "yes"
    - name: "Set owner of data folder"
      file:
        path: "{{ data_folder_destination }}"
        owner: "{{ owner_destination }}"
        group: "{{ group_destination }}"
        state: "directory"
        recurse: "yes"

- name: "Configure plugins"
  hosts: application_destination
  tags:
    - "uncheckable"
  tasks:
    - name: "Put wabue plugin at the end of the plugin ist"
      tags:
        - "uncheckable"
      command: "php vendor/bin/elgg-cli wabue:prioritize chdir={{ application_folder_destination }}"
    - name: "Configure plugins"
      tags:
        - "uncheckable"
      command: "php vendor/bin/elgg-cli wabue:configure chdir={{ application_folder_destination }}"

- name: "Set announcement banner"
  hosts: application_destination
  tags:
    - "uncheckable"
    - "integration"
  tasks:
    - name: "Set announcement banner"
      command: "php vendor/bin/elgg-cli wabue:announcement -- '{{ announcement }}' chdir={{ application_folder_destination }}"
      when: announcement != ""

- name: "Clean up locally"
  tags:
    - "always"
  hosts: ansible_master
  tasks:
    - name: "Remove local tempdir"
      file:
        path: "{{ local_tempdir.path }}"
        state: "absent"