playbook:
  hosts:
    # The master host running the playbook (required for copy/fetch tasks)
    ansible_master:
      ansible_connection: "local"
    # Database hosts
    database_source:
      ansible_host: "FIXME"
      ansible_user: "FIXME"
    database_destination:
      ansible_host: "FIXME"
      ansible_user: "FIXME"
    # Application hosts
    application_source:
      ansible_host: "FIXME"
      ansible_user: "FIXME"
    application_destination:
      ansible_host: "FIXME"
      ansible_user: "FIXME"
  vars:
    # Database hosts, names and users
    database_source_host: "localhost"
    database_source_name: "FIXME"
    database_source_username: "FIXME"
    database_source_password: !vault |
      $ANSIBLE_VAULT;secrets
    database_destination_host: "FIXME"
    database_destination_name: "FIXME"
    database_destination_username: "FIXME"
    database_destination_password: !vault |
      $ANSIBLE_VAULT;secrets

    # Base URL of source and destination environment
    url_source: "FIXME"
    url_destination: "FIXME"

    # Path of datafolder on source and destination
    data_folder_source: "FIXME"
    data_folder_destination: "FIXME"

    # Path of application on source and destination
    application_folder_source: "FIXME"
    application_folder_destination: "FIXME"

    # Run update tasks on the destination host
    update_tasks:

    # Run update sql scripts on the destination database host
    update_tasks_sql:

    # Owner and group that should be set on the application and data paths on destijnation
    owner_destination: "www-data"
    group_destination: "www-data"

    # An announcement to set
    announcement: ""