- name: "{{ item['mod'] }} - Remove mod"
  file: 
    path: "{{ application_folder_destination }}/mod/{{ item['mod'] }}"
    state: "absent"
  ignore_errors: "yes"
- name: "{{ item['mod'] }} - Download new mod"
  get_url:
    url: "{{ item['url'] }}"
    dest: "{{ application_folder_destination }}/mod/download_module"
- name: "{{ item['mod'] }} - Unarchive mod"
  tags:
    - "uncheckable"
  unarchive:
    src: "{{ application_folder_destination }}/mod/download_module"
    dest: "{{ application_folder_destination }}/mod"
    owner: "{{ owner_destination }}"
    group: "{{ group_destination }}"
- name: "{{ item['mod'] }} - Remove archive"
  file:
    path: "{{ application_folder_destination }}/mod/download_module"
    state: "absent"
- name: "{{ item['mod'] }} - Rename folder"
  tags:
    - "uncheckable"
  command: "mv {{ item['rename_from'] }} {{ item['rename_to'] }} chdir={{ application_folder_destination }}/mod"
  when: "item['rename_from'] is defined and item['rename_to'] is defined"