- name: "Remove mod"
  file: 
    path: "{{ application_folder_destination }}/mod/{{ item['mod'] }}"
    state: "absent"
  ignore_errors: "yes"
- name: "Download new mod"
  get_url:
    url: "{{ item['url'] }}"
    dest: "{{ application_folder_destination }}/mod"
- name: "Unarchive mod"
  unarchive:
    src: "{{ application_folder_destination }}/mod/{{ item['archive'] }}"
    dest: "{{ application_folder_destination }}/mod"
- name: "Remove archive"
  file:
    path: "{{ application_folder_destination }}/mod/{{ item['archive'] }}"
    state: "absent"
- name: "Rename folder"
  command: "mv {{ item['rename_from'] }} {{ item['rename_to'] }} chdir={{ application_folder_destination }}/mod"
  when: "item['rename_from'] is defined and item['rename_to'] is defined"