- name: "Create tempfile"
  tempfile:
  register: "update_sql_tempfile"
- name: "Upload script"
  copy:
    src: "updates_sql/{{ update_task_sql }}.sql"
    dest: "{{ update_sql_tempfile.path }}"
- name: "Run script"
  mysql_db:
    state: "import"
    name: "{{ database_destination_name }}"
    login_user: "{{ database_destination_username }}"
    login_password: "{{ database_destination_password }}"
    target: "{{ update_sql_tempfile.path }}"
- name: "Cleanup"
  file:
    path: "{{ update_sql_tempfile.path }}"
    state: "absent"
