version: "3.7"
services:
    db:
      image: "mariadb:10"
      environment: 
        MYSQL_ROOT_PASSWORD: "secret"
        MYSQL_DATABASE: "mitglieder"
        MYSQL_USER: "mitglieder"
        MYSQL_PASSWORD: "mitglieder"
      volumes:
        - "./db:/var/lib/mysql"
    web:
      image: "wabuehamm/web.members:latest"
      volumes:
        - "./site:/var/www/localhost/htdocs:cached"
        - "./data:/srv/elgg_data:cached"
      ports:
        - "8443:8443"